### ISSUE TITLE
silently ignore unknown filetypes

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis-thumbnails#36]
```
2020-07-27T11:06:37+02:00 WRN Failed to execute error="can't be encoded. filetype -1 not supported" duration=0.125718 method=Thumbnails.GetThumbnail service=thumbnails
```
reduce to debug level logging, as this is an expected condition in daily usage, right? might also have to update the web ui to not spew errors in the browser console ... and return caching headers that tell clients not to try again if we know there won't be a thumbnail in the next 24h?

**Comment by C0rby** [comment]
This was already handled in https://github.com/owncloud/ocis-thumbnails/issues/31 https://github.com/owncloud/ocis-thumbnails/pull/33
